---
- name: Install Fail2ban
  package: name=fail2ban
  notify: Enable Fail2ban

- name: Configure jails
  template: >
    src=jail.local.j2
    dest={{ f2b_jail_path }}/{{ f2b_jail }}.local
    verify="fail2ban-client -d"
  notify: Reload Fail2ban
